name: "spotify"
version: "1.0.0"

profile: "spotify"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify:
    +static_analysis: off
    staging:
      +materialized: view

    presentation:
      +materialized: table
